### ISSUE TITLE
Can’t Load URL

### ISSUE THREAD

**Issue by MVakas** [Alex601t/Catamaran#1]
<img width="311" alt="screen shot 2016-10-17 at 10 23 32 am" src="https://cloud.githubusercontent.com/assets/7447077/19426176/d5f4e2be-9453-11e6-89f0-25c5272c8fc1.png">

I’m getting this. What am I missing here?

**Comment by Alex601t** [comment]
@MVakas check your Configurator and Facebook App settings (developers.facebook.com)
