### ISSUE TITLE
Mistakes in readme file

### ISSUE THREAD

**Issue by Gargo** [Alex601t/Catamaran#3]
From your readme:
```
An easy way to get Social Newtworks authenticating by OAuth 2.0 on Objective-C via UIWebView. Supported social networks: google, Facebook, foursquare, linkedin, instagram, mail.ru, ok.ru, yandex, vk 
```

```
An easy way to get Social Newtworks authenticating by OAuth 2.0 on Objective-C via UIWebView
```

1)You describe a list of concrete social networks. It confuses people. For example I though you support only these social networks because most of them have a public iOS SDK.
2)OAuth2.0 is used not only for social networks. For example in my case it is Wunderlist
3)Newtworks -> Networks (the same mistake in code too)

**Comment by Alex601t** [comment]
@Gargo Thx you for your opinion and thx for the bugs found
