### ISSUE TITLE
Feature request: grant_type is not hardcoded

### ISSUE THREAD

**Issue by gerchicov-bp** [Alex601t/Catamaran#5]
You hardcoded "grant_type=password" or "grant_type=authorization_code"

For example Twitch:
https://dev.twitch.tv/docs/authentication#oauth-client-credentials-flow-app-access-tokens
"grant_type" has a lot of types and it could be probably better to add this param as setting or allow to override it but not to rewrite the whole methods

**Comment by Alex601t** [comment]
@gerchicov-bp Hey! Thx for the suggestion. 

You can override methods and manipulate URL (for grand type) like this 
https://github.com/Alex601t/Catamaran/blob/master/Catamaran/Logic/SocialNetworks/GitHub/CATGitHubOAuth.m

But you're right, the code needs refactoring for more convenience. Maby you want to contribute ? :)
